//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWanderingMentat.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebsiteText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebsiteText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheWanderingMentat.Controllers.WebsiteText", typeof(WebsiteText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Column1_Header {
            get {
                return ResourceManager.GetString("Column1_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of my code previews. Demonstration of adherence to  Clean Code principles in practice while designing algorithms..
        /// </summary>
        public static string Column1_Text {
            get {
                return ResourceManager.GetString("Column1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills and Experience.
        /// </summary>
        public static string Column2_Header {
            get {
                return ResourceManager.GetString("Column2_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See which technologies i have working experience with and which i learned and practiced on my own..
        /// </summary>
        public static string Column2_Text {
            get {
                return ResourceManager.GetString("Column2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbies.
        /// </summary>
        public static string Column3_Header {
            get {
                return ResourceManager.GetString("Column3_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you wondering what i do in my free time? Let me share my passion with you..
        /// </summary>
        public static string Column3_Text {
            get {
                return ResourceManager.GetString("Column3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout App.
        /// </summary>
        public static string Column4_Header {
            get {
                return ResourceManager.GetString("Column4_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How good am I at Intergrating tech such as MVC, Entity Framework and algorithms implemented in C#? Click to find out..
        /// </summary>
        public static string Columnt4_Text {
            get {
                return ResourceManager.GetString("Columnt4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to contact me.
        /// </summary>
        public static string Contact_Header {
            get {
                return ResourceManager.GetString("Contact_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn etc.
        /// </summary>
        public static string Contact_Text {
            get {
                return ResourceManager.GetString("Contact_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Hawat!.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test subgreet.
        /// </summary>
        public static string Sub_Greeting {
            get {
                return ResourceManager.GetString("Sub_Greeting", resourceCulture);
            }
        }
    }
}
